# np.zeros()

In [1]:
### np.zeros()

import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.zeros((5, 5)).shape

(5, 5)

In [5]:
np.zeros((5, 5)).ndim

2

# np.ones()

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.ones((5,5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

# np.full()

In [8]:
# list of size 10, all filled with value 5

In [9]:
np.full((5,5), 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
np.full((5,5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [11]:
np.full(10, 5)
# np.full(shape, fill_value)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# np.eye(n)

In [12]:
np.eye(6, 6, 4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# np.empty(shape)

In [13]:
a = np.full((5,5), 0)

In [14]:
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# np.empty(shape)

In [15]:
np.empty((5,5))

array([[ 1.15706896e-306,  1.33512173e-306,  2.22379627e-096,
        -1.74103569e-310,  4.52787157e-159],
       [ 9.43137709e-313,  4.28354915e-321,  2.17292369e-311,
         7.72367638e-304,  1.15712261e-306],
       [ 0.00000000e+000,  7.26511046e-292,  2.27065077e-312,
         1.87597231e-311,  0.00000000e+000],
       [ 1.25990589e-300,  0.00000000e+000,  1.15712261e-306,
         0.00000000e+000,  6.42261462e+045],
       [ 6.89715642e-321, -1.81530551e-310,  1.63321133e-301,
         3.43224440e-317,  5.69119271e-311]])

In [16]:
np.empty((5,5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 1, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [17]:
np.empty((5,5), dtype=int)

array([[   29836540811477108,    30962737072111727,  3175882162233409633,
        -9223336797900150934,  2238240857893080083],
       [        190893197520,                  867,        4398046511104,
           72324775363478272,    29836880117170176],
       [                   0,   251357154378383740,         459584831868,
               3797010219008,                    0],
       [  120189815083106916,                    0,    29836880132178306,
                           0,  5292292512113755243],
       [                1396, -9223335294662187149,   106960491150049280,
                     6946940,       11519102287872]])

In [18]:
import time

perf_counter() is used to get high-resolution time counter.

In [19]:
start_e = time.perf_counter()
np.empty((5, 5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)

8.759996853768826e-05


In [20]:
start_we = time.perf_counter()
np.ones((5, 5))
end_we = time.perf_counter()
total_we = end_we - start_we
print(total_we)

0.00029719993472099304


# np.random.rand(shape)

In [21]:
np.random.rand(5,5)

array([[0.82360071, 0.01112223, 0.20873445, 0.91332116, 0.67015343],
       [0.50465434, 0.39969807, 0.63170344, 0.35458785, 0.54574556],
       [0.13184554, 0.22474631, 0.15142412, 0.31921387, 0.31579734],
       [0.63413903, 0.21289969, 0.98833791, 0.27731963, 0.76024013],
       [0.37181373, 0.97872097, 0.73300728, 0.60913026, 0.85427024]])

In [22]:
a = np.random.rand(10)*10

In [23]:
a = a.tolist()

In [24]:
a

[7.084953259280207,
 3.5321828948118172,
 1.0777972964357152,
 3.9221914620043186,
 8.246496132205085,
 6.230048895432169,
 9.246960732493354,
 3.750617056498744,
 6.160012847111247,
 0.9789154356909524]

In [25]:
a = [int(i) for i in a]

In [26]:
a

[7, 3, 1, 3, 8, 6, 9, 3, 6, 0]

In [27]:
a

[7, 3, 1, 3, 8, 6, 9, 3, 6, 0]

In [28]:
np.random.randint(1, 11, 10)

array([10,  4,  1,  4,  2,  1,  2,  1,  5,  5], dtype=int32)

# Questions
- A 1D array of numbers from 0 to 9
- A 3x3 matrix of all 5s
- A 4x4 identity matrix
- 10 evenly spaced numbers between 1 and 100
- A 2x2 array with random values between 0 and 1

# Answers


A 1D array of numbers from 0 to 9
```bash
arr1 = np.arange(10)
print(arr1)
```

A 3x3 matrix of all 5s
```bash
arr2 = np.full((3, 3), 5)
print(arr2)
```

A 4x4 identity matrix
```bash
arr3 = np.eye(4)
print(arr3)
```

10 evenly spaced numbers between 1 and 100
```bash
arr4 = np.linspace(1, 100, 10)
print(arr4)
```

A 2x2 array with random values between 0 and 1
```bash
arr5 = np.random.rand(2, 2)
print(arr5)
```

# numpy attributes

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [30]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [31]:
arr.shape

(2, 3)

In [32]:
arr.ndim

2

In [33]:
arr.dtype

dtype('int64')

# ndarray.itemsize

In [34]:
arr.itemsize # size in bytes of one element

8

In [35]:
# 1 gb --> 1024 mb
# 1 mb --> 1024 kb
# 1 kb --> 1024 bytes
# 1 byte --> 8 bit

# Java
# - int --> 4 bytes
# - float --> 4 bytes
# - char --> 1 byte

In [36]:
# import sys

# print("Size of int:", sys.getsizeof(int()))  # Integer
# print("Size of float:", sys.getsizeof(float()))  # Floating-point number
# print("Size of str:", sys.getsizeof(str()))  # String
# print("Size of list:", sys.getsizeof(list()))  # List
# print("Size of tuple:", sys.getsizeof(tuple()))  # Tuple
# print("Size of dict:", sys.getsizeof(dict()))  # Dictionary
# print("Size of set:", sys.getsizeof(set()))  # Set


In [37]:
arr.nbytes # total number of bytes consumed by the array

48

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
a = np.array([[1,2,3], [4,5,6]])

In [42]:
print(a.shape)
print(a.T.shape)

(2, 3)
(3, 2)


In [43]:
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [44]:
z = np.full((3,5),3)
print(z)
z = z.T
print(z)


[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


# indexing and slicing

In [45]:
arr = np.array([10,20,30,40,50,60])

In [46]:
print(arr[0])
print(arr[-1])

10
60


In [47]:
print(arr[1:4])
print(arr[:3])
print(arr[0:3])

[20 30 40]
[10 20 30]
[10 20 30]


In [48]:
print(arr[::2]) # (start with 0 and step size 2)


[10 30 50]


In [49]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [50]:
print(mat[0,1])
print(mat[1])
print(mat[:,2])
print(mat[:,-1])

2
[4 5 6]
[3 6 9]
[3 6 9]


In [51]:
print(mat[0:2,1:])

[[2 3]
 [5 6]]


In [52]:
arr_temp = np.array([1,2,3,4,5,6,7,8,9])

In [53]:
arr_temp[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [54]:
# [[9, 8, 7],
# [6, 5, 4],
# [3, 2, 1]]

print(mat[::-1, ::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [55]:
arr = np.array([5, 10, 15, 20, 25])

In [56]:
arr>10

array([False, False,  True,  True,  True])

In [57]:
print(arr[arr>10]) # boolean indexing

[15 20 25]


In [58]:
indx = [0,3,4]
arr[indx]

array([ 5, 20, 25])

In [59]:
arr[0] = 50
print(arr)

[50 10 15 20 25]


# indexing with np.where()

In [60]:
arr = np.array([10, 15, 20, 25, 30])

In [61]:
idx = np.where(arr>20)
print(idx)

(array([3, 4]),)


In [62]:
print(arr[idx])

[25 30]


# array reshaping and resizing

In [63]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [64]:
arr.shape

(6,)

In [65]:
reshaped = arr.reshape(2,3)

In [66]:
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [67]:
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10,11,12])

In [68]:
reshaped = arr.reshape(3,-1)

In [69]:
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
reshaped.shape

(3, 4)

In [71]:
a = np.array([[1, 2], [3, 4]])

In [72]:
b = a.flatten()

In [73]:
b

array([1, 2, 3, 4])

In [74]:
a = np.array([1, 2, 3, 4])

In [75]:
a.resize((2,3))

In [76]:
print(a)

[[1 2 3]
 [4 0 0]]


In [77]:
a = np.array([1, 2, 3, 4])

In [78]:
a.resize((2,1))

In [79]:
print(a)

[[1]
 [2]]


In [80]:
# reshape will throw error if values are insufficient
# resize will truncate or padd with zeros

In [81]:
12, (4,5)--> 20 --> reshape will throw error
12, (4,5) --> 20 --> resize, it will pad extra element with 0

12-> 8--> 0

SyntaxError: invalid syntax (3561788237.py, line 1)

In [ ]:
a = np.array([[[1],[2],[3]], [[1],[2],[3]]])
print(a.shape)

(2, 3, 1)


In [ ]:
a = np.array([[1],[2],[3]])
print(a.shape)

(3, 1)


In [ ]:
a = np.array([[[1],[2],[3]]])
print(a.shape)

(1, 3, 1)


In [ ]:
a = np.array([[[1],[2],[3]], [[1],[2],[3]]])
print(a.shape)
b = np.squeeze(a)
print(b.shape)
print(b)

(2, 3, 1)
(2, 3)
[[1 2 3]
 [1 2 3]]


In [ ]:
b = np.squeeze(a)
print(b.shape)
print(b)

(3,)
[1 2 3]


In [ ]:
a = np.array([[[1],[2],[3]]])
print(a.shape)
b = np.squeeze(a, axis=0)
print(b.shape)
print(b)

(1, 3, 1)
(3, 1)
[[1]
 [2]
 [3]]


In [ ]:
b = np.array([b])
print(b)

[[1 2 3]]


In [ ]:
a = np.array([
                [1,2,3],
                [1,2,3],
                [1,2,3]
            ])

In [ ]:
print(np.sum(a, axis=0)) # rows wise

[3 6 9]


In [ ]:
print(np.sum(a, axis=1)) # column wise

[6 6 6]
