# np.zeros()

In [1]:
### np.zeros()

import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.zeros((5, 5)).shape

(5, 5)

In [5]:
np.zeros((5, 5)).ndim

2

# np.ones()

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.ones((5,5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

# np.full()

In [8]:
# list of size 10, all filled with value 5

In [9]:
np.full((5,5), 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
np.full((5,5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [11]:
np.full(10, 5)
# np.full(shape, fill_value)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# np.eye(n)

In [12]:
np.eye(6, 6, 4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# np.empty(shape)

In [13]:
a = np.full((5,5), 0)

In [14]:
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# np.empty(shape)

In [15]:
np.empty((5,5))

array([[1.15623214e-311, 0.00000000e+000, 0.00000000e+000,
        1.15623214e-311, 0.00000000e+000],
       [3.45845952e-323, 1.15623214e-311, 1.15623214e-311,
        0.00000000e+000, 4.03179200e-313],
       [4.45619116e-313, 0.00000000e+000, 1.15623214e-311,
        0.00000000e+000, 0.00000000e+000],
       [1.15623214e-311, 0.00000000e+000, 3.45845952e-323,
        1.15623214e-311, 1.15623214e-311],
       [0.00000000e+000, 4.03179200e-313, 4.45619116e-313,
        5.58294180e-321, 1.15623214e-311]])

In [16]:
np.empty((5,5), dtype=np.int8)

array([[1, 0, 0, 1, 0],
       [1, 1, 1, 0, 1],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1]], dtype=int8)

In [17]:
np.empty((5,5), dtype=int)

array([[2340239902824,             0,             0, 2340239902848,
                    0],
       [            7, 2340239902832, 2340239902808,             0,
          81604378649],
       [  90194313241,             0, 2340239902920,             0,
                    0],
       [2340239902944,             0,             7, 2340239902928,
        2340239902904],
       [            0,   81604378649,   90194313241,          1130,
        2340239902856]])

In [18]:
import time

perf_counter() is used to get high-resolution time counter.

In [19]:
start_e = time.perf_counter()
np.empty((5, 5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)

7.369997911155224e-05


In [20]:
start_we = time.perf_counter()
np.ones((5, 5))
end_we = time.perf_counter()
total_we = end_we - start_we
print(total_we)

0.0003614000743255019


# np.random.rand(shape)

In [21]:
np.random.rand(5,5)

array([[0.2103773 , 0.84333429, 0.78056544, 0.71843491, 0.7511394 ],
       [0.40130245, 0.59980086, 0.21602844, 0.92473521, 0.22193293],
       [0.87323876, 0.6982999 , 0.17698871, 0.61066798, 0.29063571],
       [0.26878899, 0.08165978, 0.4356622 , 0.73319303, 0.84322139],
       [0.03596751, 0.6805978 , 0.0676481 , 0.26584322, 0.40746317]])

In [22]:
a = np.random.rand(10)*10

In [23]:
a = a.tolist()

In [24]:
a

[5.468894006562534,
 1.6232626767811786,
 7.8651882659080545,
 9.597975509000385,
 5.45551060670682,
 2.6190168338938467,
 1.7907115458510947,
 3.9864169905997224,
 2.0434069178851844,
 3.596854885902675]

In [25]:
a = [int(i) for i in a]

In [26]:
a

[5, 1, 7, 9, 5, 2, 1, 3, 2, 3]

In [27]:
a

[5, 1, 7, 9, 5, 2, 1, 3, 2, 3]

In [28]:
np.random.randint(1, 11, 10)

array([ 2,  8,  3,  9,  7,  2,  2,  7,  1, 10], dtype=int32)

# Questions
- A 1D array of numbers from 0 to 9
- A 3x3 matrix of all 5s
- A 4x4 identity matrix
- 10 evenly spaced numbers between 1 and 100
- A 2x2 array with random values between 0 and 1

# Answers


A 1D array of numbers from 0 to 9
```bash
arr1 = np.arange(10)
print(arr1)
```

A 3x3 matrix of all 5s
```bash
arr2 = np.full((3, 3), 5)
print(arr2)
```

A 4x4 identity matrix
```bash
arr3 = np.eye(4)
print(arr3)
```

10 evenly spaced numbers between 1 and 100
```bash
arr4 = np.linspace(1, 100, 10)
print(arr4)
```

A 2x2 array with random values between 0 and 1
```bash
arr5 = np.random.rand(2, 2)
print(arr5)
```

# numpy attributes

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [30]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [31]:
arr.shape

(2, 3)

In [32]:
arr.ndim

2

In [33]:
arr.dtype

dtype('int64')

# ndarray.itemsize

In [34]:
arr.itemsize # size in bytes of one element

8

In [35]:
# 1 gb --> 1024 mb
# 1 mb --> 1024 kb
# 1 kb --> 1024 bytes
# 1 byte --> 8 bit

# Java
# - int --> 4 bytes
# - float --> 4 bytes
# - char --> 1 byte

In [36]:
# import sys

# print("Size of int:", sys.getsizeof(int()))  # Integer
# print("Size of float:", sys.getsizeof(float()))  # Floating-point number
# print("Size of str:", sys.getsizeof(str()))  # String
# print("Size of list:", sys.getsizeof(list()))  # List
# print("Size of tuple:", sys.getsizeof(tuple()))  # Tuple
# print("Size of dict:", sys.getsizeof(dict()))  # Dictionary
# print("Size of set:", sys.getsizeof(set()))  # Set


In [37]:
arr.nbytes # total number of bytes consumed by the array

48

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
a = np.array([[1,2,3], [4,5,6]])

In [42]:
print(a.shape)
print(a.T.shape)

(2, 3)
(3, 2)


In [43]:
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [44]:
z = np.full((3,5),3)
print(z)
z = z.T
print(z)


[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]
