In [1]:
import numpy as np

In [2]:
# Create a 6x6 identity-like matrix (ones on diagonal, zeros elsewhere)
matrix = np.eye(6, 6)

print(matrix)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [3]:
np.eye(6,6,4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
# np.empty(shape)

In [5]:
np.full((5,5),0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
# Generate a 2x3 matrix with random floats between 0 and 1
random_matrix = np.random.rand(2, 3)

print(random_matrix)

[[0.30196479 0.23865311 0.57579444]
 [0.55370679 0.58075207 0.4556726 ]]


In [7]:
# Generate 10 random float numbers between 0 and 10
a = np.random.rand(10) * 10

# Convert NumPy array to Python list
a = a.tolist()

# Display the list
print(a)

[6.65211675715266, 4.6683653725827226, 3.8901668042955064, 4.547251426119427, 8.214285208179668, 5.553417773270909, 7.500289760758784, 1.5772884973695456, 3.2064387363292735, 1.3617816916890901]


In [8]:
# Generate 10 random float numbers between 0 and 10
a = np.random.rand(10) * 20

# Convert NumPy array to Python list
a = a.tolist()

# Display the list
print(a)

[12.960744974486397, 5.7632153825216275, 5.495095766525042, 12.223406938217385, 14.9427321091414, 3.8955755091018984, 5.216237611009862, 11.002418244887718, 4.195821750933664, 17.71313845768177]


In [9]:
# Step 1: Generate 10 random floats between 0 and 10
a = np.random.rand(10) * 10

# Step 2: Convert to list
a = a.tolist()

# Step 3: Convert float values to integers (truncating)
a = [int(i) for i in a]

print(a)

[9, 4, 6, 2, 6, 8, 8, 9, 7, 3]


In [10]:
dice_rolls = np.random.randint(1, 7, size=10)
print("Dice Rolls:", dice_rolls.tolist())


Dice Rolls: [4, 5, 4, 5, 6, 5, 5, 1, 4, 1]


In [11]:
a = np.random.rand(5) * 100
a = [round(i, 2) for i in a]
print("Rounded values:", a)


Rounded values: [np.float64(59.22), np.float64(84.59), np.float64(93.55), np.float64(41.38), np.float64(46.66)]


In [12]:
matrix = np.random.randint(1, 10, size=(3, 3))
print("3x3 Random Matrix:\n", matrix)


3x3 Random Matrix:
 [[6 8 4]
 [1 6 5]
 [9 2 5]]


In [13]:
a = [int(i) for i in np.random.rand(15)*10]
evens = [i for i in a if i % 2 == 0]
print("Original:", a)
print("Evens only:", evens)


Original: [4, 5, 4, 4, 4, 7, 0, 2, 9, 1, 3, 3, 7, 7, 0]
Evens only: [4, 4, 4, 4, 0, 2, 0]


In [14]:
arr = np.random.randint(10, 100, size=8)
print("Array:", arr)
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Mean:", np.mean(arr))


Array: [17 72 94 80 48 33 21 33]
Min: 17
Max: 94
Mean: 49.75


In [15]:
# Use np.random to simulate fake data for testing
ages = np.random.randint(18, 60, 1000)     # simulate age data
salaries = np.random.normal(50000, 10000, 1000)  # simulate salary with normal distribution


In [16]:
# Rounding and converting data
values = np.random.rand(10) * 100
cleaned = [int(v) for v in values]  # remove float noise


In [17]:
X = np.random.rand(100, 5)   # 100 rows, 5 features
y = np.random.randint(0, 2, 100)  # binary labels for classification


In [18]:
data = np.random.randint(1, 100, 50)
print("Mean:", np.mean(data))
print("Std Dev:", np.std(data))
print("Median:", np.median(data))


Mean: 49.28
Std Dev: 28.165965277263272
Median: 52.5


In [19]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
result = np.dot(A, B)  # matrix multiplication


In [20]:
np.random.randint(1,11,10)

array([1, 8, 4, 4, 3, 1, 8, 9, 4, 5], dtype=int32)

In [21]:
import numpy as np

# Assignment 1: A 1D array of numbers from 0 to 9
arr1 = np.arange(10)
print("Assignment 1:", arr1)

# Assignment 2: A 3x3 matrix of all 5s
arr2 = np.full((3, 3), 5)
print("Assignment 2:\n", arr2)

# Assignment 3: A 4x4 identity matrix
arr3 = np.eye(4)
print("Assignment 3:\n", arr3)

# Assignment 4: 10 evenly spaced numbers between 1 and 100
arr4 = np.linspace(1, 100, 10)
print("Assignment 4:", arr4)


Assignment 1: [0 1 2 3 4 5 6 7 8 9]
Assignment 2:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Assignment 3:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Assignment 4: [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [22]:
import numpy as np

# 1. A 1D array of numbers from 0 to 9
arr1 = np.arange(10)
print("1D array from 0 to 9:\n", arr1)

# 2. A 3x3 matrix of all 5s
arr2 = np.full((3, 3), 5)
print("\n3x3 matrix of 5s:\n", arr2)

# 3. A 4x4 identity matrix
arr3 = np.eye(4)
print("\n4x4 identity matrix:\n", arr3)

# 4. 10 evenly spaced numbers between 1 and 100
arr4 = np.linspace(1, 100, 10)
print("\n10 evenly spaced numbers between 1 and 100:\n", arr4)

# 5. A 2x2 array with random values between 0 and 1
arr5 = np.random.rand(2, 2)
print("\n2x2 array with random values:\n", arr5)


1D array from 0 to 9:
 [0 1 2 3 4 5 6 7 8 9]

3x3 matrix of 5s:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

4x4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

10 evenly spaced numbers between 1 and 100:
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]

2x2 array with random values:
 [[0.06353991 0.05128812]
 [0.83622    0.03107938]]
