In [1]:
import numpy as np

In [2]:
# Create a 6x6 identity-like matrix (ones on diagonal, zeros elsewhere)
matrix = np.eye(6, 6)

print(matrix)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [3]:
np.eye(6,6,4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
# np.empty(shape)

In [5]:
np.full((5,5),0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
# Generate a 2x3 matrix with random floats between 0 and 1
random_matrix = np.random.rand(2, 3)

print(random_matrix)

[[0.30196479 0.23865311 0.57579444]
 [0.55370679 0.58075207 0.4556726 ]]


In [7]:
# Generate 10 random float numbers between 0 and 10
a = np.random.rand(10) * 10

# Convert NumPy array to Python list
a = a.tolist()

# Display the list
print(a)

[6.65211675715266, 4.6683653725827226, 3.8901668042955064, 4.547251426119427, 8.214285208179668, 5.553417773270909, 7.500289760758784, 1.5772884973695456, 3.2064387363292735, 1.3617816916890901]


In [8]:
# Generate 10 random float numbers between 0 and 10
a = np.random.rand(10) * 20

# Convert NumPy array to Python list
a = a.tolist()

# Display the list
print(a)

[12.960744974486397, 5.7632153825216275, 5.495095766525042, 12.223406938217385, 14.9427321091414, 3.8955755091018984, 5.216237611009862, 11.002418244887718, 4.195821750933664, 17.71313845768177]


In [9]:
# Step 1: Generate 10 random floats between 0 and 10
a = np.random.rand(10) * 10

# Step 2: Convert to list
a = a.tolist()

# Step 3: Convert float values to integers (truncating)
a = [int(i) for i in a]

print(a)

[9, 4, 6, 2, 6, 8, 8, 9, 7, 3]


In [10]:
dice_rolls = np.random.randint(1, 7, size=10)
print("Dice Rolls:", dice_rolls.tolist())


Dice Rolls: [4, 5, 4, 5, 6, 5, 5, 1, 4, 1]


In [11]:
a = np.random.rand(5) * 100
a = [round(i, 2) for i in a]
print("Rounded values:", a)


Rounded values: [np.float64(59.22), np.float64(84.59), np.float64(93.55), np.float64(41.38), np.float64(46.66)]


In [12]:
matrix = np.random.randint(1, 10, size=(3, 3))
print("3x3 Random Matrix:\n", matrix)


3x3 Random Matrix:
 [[6 8 4]
 [1 6 5]
 [9 2 5]]


In [13]:
a = [int(i) for i in np.random.rand(15)*10]
evens = [i for i in a if i % 2 == 0]
print("Original:", a)
print("Evens only:", evens)


Original: [4, 5, 4, 4, 4, 7, 0, 2, 9, 1, 3, 3, 7, 7, 0]
Evens only: [4, 4, 4, 4, 0, 2, 0]


In [14]:
arr = np.random.randint(10, 100, size=8)
print("Array:", arr)
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Mean:", np.mean(arr))


Array: [17 72 94 80 48 33 21 33]
Min: 17
Max: 94
Mean: 49.75


In [15]:
# Use np.random to simulate fake data for testing
ages = np.random.randint(18, 60, 1000)     # simulate age data
salaries = np.random.normal(50000, 10000, 1000)  # simulate salary with normal distribution


In [16]:
# Rounding and converting data
values = np.random.rand(10) * 100
cleaned = [int(v) for v in values]  # remove float noise


In [17]:
X = np.random.rand(100, 5)   # 100 rows, 5 features
y = np.random.randint(0, 2, 100)  # binary labels for classification


In [18]:
data = np.random.randint(1, 100, 50)
print("Mean:", np.mean(data))
print("Std Dev:", np.std(data))
print("Median:", np.median(data))


Mean: 49.28
Std Dev: 28.165965277263272
Median: 52.5


In [19]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
result = np.dot(A, B)  # matrix multiplication


In [20]:
np.random.randint(1,11,10)

array([1, 8, 4, 4, 3, 1, 8, 9, 4, 5], dtype=int32)

In [21]:
import numpy as np

# Assignment 1: A 1D array of numbers from 0 to 9
arr1 = np.arange(10)
print("Assignment 1:", arr1)

# Assignment 2: A 3x3 matrix of all 5s
arr2 = np.full((3, 3), 5)
print("Assignment 2:\n", arr2)

# Assignment 3: A 4x4 identity matrix
arr3 = np.eye(4)
print("Assignment 3:\n", arr3)

# Assignment 4: 10 evenly spaced numbers between 1 and 100
arr4 = np.linspace(1, 100, 10)
print("Assignment 4:", arr4)


Assignment 1: [0 1 2 3 4 5 6 7 8 9]
Assignment 2:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Assignment 3:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Assignment 4: [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [22]:
import numpy as np

# 1. A 1D array of numbers from 0 to 9
arr1 = np.arange(10)
print("1D array from 0 to 9:\n", arr1)

# 2. A 3x3 matrix of all 5s
arr2 = np.full((3, 3), 5)
print("\n3x3 matrix of 5s:\n", arr2)

# 3. A 4x4 identity matrix
arr3 = np.eye(4)
print("\n4x4 identity matrix:\n", arr3)

# 4. 10 evenly spaced numbers between 1 and 100
arr4 = np.linspace(1, 100, 10)
print("\n10 evenly spaced numbers between 1 and 100:\n", arr4)

# 5. A 2x2 array with random values between 0 and 1
arr5 = np.random.rand(2, 2)
print("\n2x2 array with random values:\n", arr5)


1D array from 0 to 9:
 [0 1 2 3 4 5 6 7 8 9]

3x3 matrix of 5s:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

4x4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

10 evenly spaced numbers between 1 and 100:
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]

2x2 array with random values:
 [[0.06353991 0.05128812]
 [0.83622    0.03107938]]


In [23]:
import numpy as np

# Original matrix (2x3)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Transpose (3x2)
transposed = matrix.T

print("Original:\n", matrix)
print("Transposed:\n", transposed)


Original:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


In [24]:
import numpy as np

# Two matrices A (2x3) and B (2x3)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Vectorized multiplication using transpose
result = np.dot(A, B.T)

print("A:\n", A)
print("B:\n", B)
print("B Transposed:\n", B.T)
print("Result of A x B.T:\n", result)


A:
 [[1 2 3]
 [4 5 6]]
B:
 [[ 7  8  9]
 [10 11 12]]
B Transposed:
 [[ 7 10]
 [ 8 11]
 [ 9 12]]
Result of A x B.T:
 [[ 50  68]
 [122 167]]


In [26]:
a=np.array([[1,2,3],[4,5,6]])

In [27]:
print(a.shape)

(2, 3)


In [28]:
print(a.T.shape)

(3, 2)


In [29]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
import numpy as np

# 2D array (3x4)
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

# Indexing
element = arr[1, 2]        # Element at row 1, column 2 → 70

# Slicing
row_slice = arr[1, :]      # Entire 2nd row → [50 60 70 80]
col_slice = arr[:, 2]      # Entire 3rd column → [30 70 110]
sub_array = arr[0:2, 1:3]  # Rows 0–1, Columns 1–2 → [[20 30], [60 70]]

print("Element at [1,2]:", element)
print("Row slice:", row_slice)
print("Column slice:", col_slice)
print("Sub-array:\n", sub_array)


Element at [1,2]: 70
Row slice: [50 60 70 80]
Column slice: [ 30  70 110]
Sub-array:
 [[20 30]
 [60 70]]


In [31]:
arr=np.array([10,20,30,40,50,60])
print(arr[0])
print(arr[-1])

10
60


In [33]:
print(arr[1:])
print(arr[1:4])
print(arr[-1])
print(arr[0:3])

[20 30 40 50 60]
[20 30 40]
60
[10 20 30]


In [35]:
print(arr[::2]) #step size of 2

[10 30 50]


In [36]:
mat=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [37]:
print(mat[0,1])

2


In [38]:
print(mat[1])

[4 5 6]


In [40]:
print(mat[:,2])
print(mat[:,-1])

[3 6 9]
[3 6 9]


In [45]:
print(mat[::-1,::-1]) #row and column reverse

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [49]:
print(arr)
arr[0]=40
print(arr)

[40 20 30 40 50 60]
[40 20 30 40 50 60]


In [51]:
arr=np.array([10,20,30,40,50,60]) #where
idx=np.where(arr>20)
print(idx)

(array([2, 3, 4, 5]),)


In [56]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape((2, 3))  # Shape becomes (2x3)

print("Original:", arr)
print("Reshaped (2x3):\n", reshaped)

arr.resize((3, 2))  # Now shape is (3x2)

print("Resized (3x2):\n", arr)

Original: [1 2 3 4 5 6]
Reshaped (2x3):
 [[1 2 3]
 [4 5 6]]
Resized (3x2):
 [[1 2]
 [3 4]
 [5 6]]


In [58]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(3,-1)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]
