# numpy math operations

In [17]:
a = [1,2,3]
b = [4,5,6]

a + b

[1, 2, 3, 4, 5, 6]

In [18]:
import numpy as np

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [20]:
print(type(a + b))

<class 'numpy.ndarray'>


In [21]:
print(a + b)

[5 7 9]


In [22]:
print(a-b)
print(a*b)
print(a/b)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [23]:
# comparison

print(a > b)
print(a < b)
print(a == b)

[False False False]
[ True  True  True]
[False False False]


In [24]:
ans = a > b
print(type(ans[0]))

<class 'numpy.bool'>


In [25]:
# logical operators

# and , or , not

x = np.array([True, False, True])
y = np.array([False, False, True])

print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x))

[False False  True]
[ True False  True]
[False  True False]


In [26]:
# biwsise operators

a = np.array([1, 2, 3])
b = np.array([0, 1, 1])

print(np.bitwise_and(a,b))
print(np.bitwise_or(a,b))

[0 0 1]
[1 3 3]


In [27]:
# modulus and power

a = np.array([10, 20, 30])
b = np.array([3, 7, 4])

print(np.mod(a, b))
print(np.power(a, b))


[1 6 2]
[      1000 1280000000     810000]


# scalar opertions

In [28]:
celcius = np.array([0, 10, 20, 30])
# to_farenheit = np.array([33.8, 33.8, 33.8, 33.8]) # broadcasting
print(celcius * 9 / 5 + 32)

[32. 50. 68. 86.]


In [29]:
# # in python
# celsius = [0, 10, 20, 30]
# fahrenheit = (celsius * (9 / 5() + 32)
# print(fahrenheit)

# Common maths functions

In [30]:
a = np.array([1, 2, 3, 4])

print(np.sqrt(a))
print(np.exp(a)) # e^1, e^2, where e = 2.718, pi = 3.14
print(np.log(a))
print(np.sin(a))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [31]:
# machine learning
# activation function

# sigmoid


x = np.array([-1, 0, 1])
sigmoid = 1 / (1 + np.exp(-x))
print(sigmoid)

[0.26894142 0.5        0.73105858]


In [32]:
# Aggregation functions

In [33]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [34]:
print(np.sum(a))

21


In [35]:
print(np.sum(a, axis=0))
# across all rows, fix the column

[5 7 9]


In [36]:
print(np.sum(a))
print(np.mean(a)) # average
print(np.std(a))
print(np.min(a))
print(np.max(a))

21
3.5
1.707825127659933
1
6


# matrix operation

In [37]:
# element-wise multiplication

In [38]:
units = np.array([100, 200, 150])
profit = np.array([10, 20, 30])

In [39]:
units * profit

array([1000, 4000, 4500])

# Dot product

In [40]:
# sqft
# bedroom
# location 1 G, 0 B

In [41]:
house = np.array([[1200, 3, 1],
                  [1200, 3, 0],
                  [1000, 3, 0],
                  [1000, 1, 1]])

In [42]:
w = np.array([200, 10000, 50000])

In [43]:
print(house.shape)
print(w.shape)

(4, 3)
(3,)


In [44]:
print(np.dot(house, w))

[320000 270000 230000 260000]


In [45]:
print(np.sum(house * w, axis=1)) # multiplication + sum

[320000 270000 230000 260000]


In [46]:
A = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
B = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

In [47]:
print(A.shape)
print(B.shape)

(2, 4)
(2, 4)


In [49]:
# print(np.dot(A, B))

In [ ]:
print(np.dot(A, B.T))

[[30 30]
 [30 30]]


In [ ]:
print(A @ B.T)

[[30 30]
 [30 30]]


# broadcasting

In [ ]:
a = np.array([1, 2, 3]) # (3,)
b = np.array([[10], [20]]) # (2,1)

In [ ]:
print(a.shape)
print(b.shape)

(3,)
(2, 1)


In [ ]:
a + b

# a --> (2,3) [[1, 2, 3], [1, 2, 3]]
# b --> [[10, 10, 10], [20, 20, 20]]

array([[11, 12, 13],
       [21, 22, 23]])

# creating arrays from exisiting data

In [ ]:
a = [1,2,3,4]
b = ([[1,2], [2,3]])
c = (10,20,30)

In [ ]:
a_npy = np.array(a)
print(a_npy, a_npy.dtype, type(a))

[1 2 3 4] int64 <class 'list'>


In [ ]:
b_npy = np.array(b)
print(b_npy, b_npy.dtype, type(b))

[[1 2]
 [2 3]] int64 <class 'list'>


In [ ]:
c_npy = np.array(c)
print(c_npy, c_npy.dtype, type(c))

[10 20 30] int64 <class 'tuple'>


In [ ]:
# vstack

a = np.array([[1,2]])
b = np.array([[3,4]])

In [ ]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [ ]:
print(np.hstack((a,b)))

[[1 2 3 4]]


In [ ]:
# np.char.<function_name>()

# 1. np.add()

# "hello" + "hello"

a = np.array(['hello', 'world'])
b = np.array(['_user', '_123'])

print(np.char.add(a, b))

['hello_user' 'world_123']


In [ ]:
# np.char.multiply()

print(np.char.multiply(a, 2))

['hellohello' 'worldworld']


In [ ]:
# np.char.upper() / lower() / capitalize()

a = np.array(['hello', 'WORLD'])

print(np.char.upper(a)) 
print(np.char.lower(a)) 
print(np.char.capitalize(a)) 

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']


In [ ]:
# np.char.center()

print(np.char.center(a, 11, fillchar='*'))

['***hello***' '***WORLD***']


In [ ]:
a = np.array(['data_science', 'machine_learning'])

In [ ]:
# np.char.replace()

print(np.char.replace(a, '_', ' '))

['data science' 'machine learning']


In [ ]:
# np.char.split()

print(np.char.split(a, sep='_'))

[list(['data', 'science']) list(['machine', 'learning'])]


In [ ]:
# np.char.find() / np.char.count()

print(np.char.find(a, 'learn')) 
print(np.char.count(a, 'a'))
print(np.char.count(a, 'data'))

[-1  8]
[2 2]
[1 0]


# statistical functions

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Min:", np.min(data))
print("Max:", np.max(data))

Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665
Min: 1
Max: 6


In [ ]:
print("Argmin:", np.argmin(data))
print("Argmax:", np.argmax(data))

Argmin: 0
Argmax: 5


In [ ]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print(np.mean(matrix, axis=0))
print(np.mean(matrix, axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [ ]:
data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50)) # range 1 - 100
print(np.quantile(data, 1)) # range 0 - 1

5.0
9


# sort, search, counting functions

In [ ]:
arr = np.array([3, 6, 1, 1, 1, 1, 8, 2, 5, 6])

print("Sorted:", np.sort(arr))
print("Sorted indices:", np.argsort(arr))
print("Insert 4 position:", np.searchsorted(np.sort(arr), 4))
print("Unique elements:", np.unique(arr))
print("Count of each element:", np.bincount(arr))

# min - 1
# max - 8
# creates an array from 0 to max element (8)
# 0, 1, 2, 3, 4, 5, 6, 7, 8 --> len(9)

Sorted: [1 1 1 1 2 3 5 6 6 8]
Sorted indices: [3 2 5 4 7 0 8 1 9 6]
Insert 4 position: 6
Unique elements: [1 2 3 5 6 8]
Count of each element: [0 4 1 1 0 1 2 0 1]


In [ ]:
arr = np.array([1, 2, 3, 4])

for x in arr:
    print(x)

1
2
3
4


In [ ]:
arr_2d = np.array([[1, 2], [3, 4]])

for x in arr_2d:
    print(x)

[1 2]
[3 4]


In [ ]:
arr = np.arange(8).reshape(2,2,2)

for x in np.nditer(arr):
    print(x)

0
1
2
3
4
5
6
7


In [ ]:
a = np.array([1, 2, 3])

In [ ]:
b = a

In [ ]:
print(id(a))
print(id(b))

2182904262896
2182904262896


In [ ]:
b[0] = 100

In [ ]:
print(a)

[100   2   3]


In [ ]:
a = np.array([1, 2, 3])

In [ ]:
b = a.copy()

In [ ]:
print(id(a))
print(id(b))

2182904263280
2182904045296


In [ ]:
b[0] = 100

In [ ]:
print(a)

[1 2 3]


In [ ]:
a = np.array([1, 2, 3])

b = a.view()

c = a.copy()

In [ ]:
b[0] = 10
print(a)

[10  2  3]


In [ ]:
c[0] = 20
print(a)

[10  2  3]


In [ ]:
a = np.arange(5)
b = a[1:4] # view
print(np.shares_memory(a, b))

True


In [ ]:
a = np.arange(5)
b = a[1:4].copy()
print(np.shares_memory(a, b))

False


In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a.ravel())
print(a.flatten())

[1 2 3 4]
[1 2 3 4]
