In [ ]:
# List concatenation in plain Python
a = [1, 2, 3]
b = [4, 5, 6]

print(a + b)  # Output: [1, 2, 3, 4, 5, 6]

# Using NumPy arrays
import numpy as np

a = np.array([1, 2, 3]) #creating numpy array from list
b = np.array([4, 5, 6])


[1, 2, 3, 4, 5, 6]


In [3]:
a+b

array([5, 7, 9])

In [5]:
print(a-b)
print(a*b)
print(a/b)


[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [6]:
import numpy as np

# bitwise operators
a = np.array([1, 2, 3])
b = np.array([0, 1, 1])

print(np.bitwise_and(a, b))  # Output: [0 0 1]


[0 0 1]
